// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcqmswpCwLfS4zBEoZdoQbd_QN2wioiaI',
    appId: '1:769875276341:web:bda0188cf5af86d707f77c',
    messagingSenderId: '769875276341',
    projectId: 'rift-tcg-dex',
    authDomain: 'rift-tcg-dex.firebaseapp.com',
    storageBucket: 'rift-tcg-dex.firebasestorage.app',
    measurementId: 'G-QG9T9JGT50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtrH1CNg0KHCGsVZtEl_ojuccP8qnqxEg',
    appId: '1:769875276341:android:e216dee6fa2dd92b07f77c',
    messagingSenderId: '769875276341',
    projectId: 'rift-tcg-dex',
    storageBucket: 'rift-tcg-dex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF_czFtYhfOE4MoqeGJ58kacSrlGxqAp8',
    appId: '1:769875276341:ios:2e4dd638aacd608807f77c',
    messagingSenderId: '769875276341',
    projectId: 'rift-tcg-dex',
    storageBucket: 'rift-tcg-dex.firebasestorage.app',
    iosBundleId: 'com.xedtcg.rift',
  );
}
